sudo: false

language: c++

dist: xenial

services:
  - docker

env:
  matrix:
    - DOCKERFILE=Dockerfile-Linux
    - DOCKERFILE=Dockerfile-Windows
script:
  - docker build -f $DOCKERFILE --build-arg SITE_URL=${SITE_URL} --build-arg SITE_TOKEN=${SITE_TOKEN} --build-arg BUILD_NUMBER=${TRAVIS_BUILD_NUMBER} --build-arg BUILD_DESCRIPTION="TravisCI-automated-build" .
