version: 2

jobs:
  build:
    docker:
      - image: arnislielturks/urho3d:12
    working_directory: ~/Urho3D-Empty-Project
    steps:
      - checkout
      - run: apt update
      - run: apt-get install -y python-setuptools curl zip
      - run: /usr/bin/x86_64-w64-mingw32-g++ --version
      - restore_cache:
          keys:
            - build-v1-{{ checksum "CMakeLists.txt" }}
            - build-v1-
      - run: bash ./script/cmake_generic.sh build -DURHO3D_HOME=/Urho3D/build || true
      - run: bash ./script/cmake_mingw.sh build-windows -DURHO3D_HOME=/Urho3D/build-windows -DMINGW_PREFIX=/usr/bin/x86_64-w64-mingw32 -DDIRECTX_LIB_SEARCH_PATHS=/usr/bin/x86-w64-mingw32/lib || true
      - run: cd build-windows && make -j 2
      - run: cd ..
      - run: cd build && make -j 2
      - run: cd ..
      - save_cache:
          key: build-v1-{{ checksum "CMakeLists.txt" }}
          paths:
            - build
